### ISSUE TITLE
Splitter dry runs should preview the output file, not the output scheme

### ISSUE THREAD

**Issue by alxmrs** [google/weather-tools#104]
The scheme or template is less powerful than reading the output that would happen from the input printed.

**Comment by uhager** [comment]
To get the actual output files, we'd have to copy, open, and parse the input files to know what values are available for the split dimensions. This would be very slow (pretty much as slow as just doing the splitting) and produce a lot of output, basically just displaying what data is in the file. 

The recent update to the weather-splitter to allow for more flexible splitting already improved the dry splitter output by using the user-provided formatting and replacing it with the split dimension names.
