### ISSUE TITLE
Thoroughly unit tests JSON Serialization

### ISSUE THREAD

**Issue by alxmrs** [google/weather-tools#106]
Check out TODO in `unit_test.py`.

**Comment by pranay101** [comment]
Hey, @alxmrs I would like to work on this issue. Please guide me further.

**Comment by alxmrs** [comment]
Sure thing Pranay. 

See the TODO in this file: https://github.com/google/weather-tools/blob/eb95533dec135d9637bc95afe09ce38b2661cf4a/weather_mv/loader_pipeline/util_test.py#L44

The task at hand is to add unit test to that file in order to totally cover every serialization case of this function: https://github.com/google/weather-tools/blob/eb95533dec135d9637bc95afe09ce38b2661cf4a/weather_mv/loader_pipeline/util.py#L29

Top priorities for testing include making sure we don't introduce any previously experienced serialization errors into our pipeline. We've had several bug in the past, tracked by issues in this project (for example, #81).

**Comment by pranay101** [comment]
hey, @alxmrs I need your help here. please guide me to what functions to test for?

**Comment by alxmrs** [comment]
Hey Pranay. How about we have a 1:1 meeting? Maybe with a code walkthrough, I can better answer your questions and/or give a good introduction to the codebase. How about next Wednesday at 9:00am PST?

**Comment by pranay101** [comment]
@alxmrs That would be so great. I'd love to be a part of it. Yes, Wednesday seems fine to me.

**Comment by alxmrs** [comment]
Great! Just added a meeting to your calendar for 10am PST this Wednesday.
