### ISSUE TITLE
Developer Installation on Linux takes 12+ hours

### ISSUE THREAD

**Issue by ksic8** [google/weather-tools#119]
While setting up DEV environment on Linux, the following command takes more than 12 hours to complete.

`pip install -e ."[dev]"`

Reference: [Developer Installation](https://github.com/google/weather-tools/blob/main/CONTRIBUTING.md#developer-installation)

Command Installation [Snap](https://drive.google.com/file/d/1iGvwlGrcaMc_vwCOZonU9ROQOUvOKyc6/view?usp=sharing)

**Comment by alxmrs** [comment]
This issue seem related to https://github.com/pypa/pip/issues/9187.

Here are fairly current workarounds to address this issue: https://stackoverflow.com/a/65793484

A short term fix, to get your dev environments set up on Linux, is to use the `--use-deprecated=legacy-resolver` flag during the pip install. A longer-term fix for this project would be to pin down package versions for each dependency. We also need to verify if simply upgrading pip will fix this issue. If it does, we need to update our contributing instructions to ensure developers follow this step.

**Comment by alxmrs** [comment]
@ksic8 Can do you the following for me? 
- Validate that this workaround makes installations faster
- If so, update the developer documentation with these instructions

**Comment by alxmrs** [comment]
Closing this issue as a solution has been documented.
