### ISSUE TITLE
The BigQuery schema should ingest grid points as polygons (covering the area a point represents). 

### ISSUE THREAD

**Issue by alxmrs** [google/weather-tools#266]
Inspired by this [post], instead of representing a grid point in a BigQuery dataset as an infinitesimally small point, we should represent it as a polygon that covers a specific area. This should help users understand the coarseness of grids, as well as apply geospatial SQL operators in BigQuery. 

Thanks @rabernat for the idea. 

[post]: https://discourse.pangeo.io/t/conservative-region-aggregation-with-xarray-geopandas-and-sparse/2715

**Comment by blackvvine** [comment]
IIUC the idea is to use a [`geojson.Polygon`](https://python-geojson.readthedocs.io/en/latest/#polygon) instead of a `Point` in the `geo_point` field:

https://github.com/google/weather-tools/blob/67affd68b509f22d3761c9e1c131ebc7c5ccd46e/weather_mv/loader_pipeline/bq.py#L333

If that is the case, what is the logic for determining the area boundaries? Do we trivially take the middle of adjacent coordinates?

In the [post](https://discourse.pangeo.io/t/conservative-region-aggregation-with-xarray-geopandas-and-sparse/2715), they are [using](https://gist.github.com/rsignell-usgs/273d5736e522017cf5d4e0d7ae691b76) a dataset which specifies the area boundaries explicitly with `lot_bounds`, `lat_bounds`, and `nv`.

**Comment by alxmrs** [comment]
Thinking about it some more: Can we add a polygon instead of replacing the point? 

For the polygon: the lat/lng point should be the center. We should check in common places within the XArray metadata (maybe, add a flag to parse arbitrary locations?) to look up the range of a grid point. 

We can more or less assume the data follows ECMWF's conventions. We aim to apply this to this dataset in particular: https://github.com/google-research/arco-era5

IIUC, I believe their coordinates are defined by the CF conventions: https://cfconventions.org/cf-conventions/cf-conventions.html#grid-mappings-and-projections

@wundersooner: I think we can decipher a way to make this issue work for ARCO datasets, but do you have any advise about what metadata we could look for to build this in a general way?

**Comment by wundersooner** [comment]
The CF conventions are the best place to look for the lat-lon grid type.  An important attribute to look for is crs_wkt, which could have the grid description in OGC WKT format.   For regular lat-lon grids, we can go with the grid point being at the center of a rectangular polygon.  Now, for Lambert Conformal and Polar Stereographic grids (which are the most likely other grids we can see in Grib files), the polygon will be a trapezoid.

**Comment by dabhicusp** [comment]
Hello, @alxmrs, based on your suggestion in the previous discussion, I explored the [arco-era5 data](https://github.com/google-research/arco-era5).  Out of the five types of data, three contain `lat-lon` information in their metadata, while the other two contain `divergence`. Unfortunately, I couldn't locate the **`crs_wkt`** attribute in the metadata of any file. 

Here is the code I used to retrieve the metadata for the data:
```
import zarr
all_data = ['gs://gcp-public-data-arco-era5/co/model-level-moisture.zarr', 
            'gs://gcp-public-data-arco-era5/co/model-level-wind.zarr',     
            'gs://gcp-public-data-arco-era5/co/single-level-forecast.zarr', 
            'gs://gcp-public-data-arco-era5/co/single-level-reanalysis.zarr',
            'gs://gcp-public-data-arco-era5/co/single-level-surface.zarr'] 
zarr_file = zarr.open(all_data[1],mode='r')
first_key = next(iter(zarr_file))
metadata = zarr_file.get(first_key).attrs
dict(metadata)
```  
The output I obtained is as follows:
This image shows the presence of `lat-lon` information in the metadata of the file:
![image](https://github.com/google/weather-tools/assets/123355381/c02c4db0-182b-46a8-85c2-e35fbd12dbd1)
This image displays the presence of `divergence` in the metadata of the file:
![image](https://github.com/google/weather-tools/assets/123355381/09a3c059-7621-4ec5-946e-445570354aea)

IIUC, for creating the polygon we are required to have [N, E, S, W](bounding box). Ref: [LINK](https://github.com/google/weather-tools/blob/main/weather_dl/download_pipeline/util.py#L138). But while ingesting in BQ a row represents a single point (lat. lon) so how can we generate polygon out of it? 

Can you assist me with the next steps to resolve this issue?

**Comment by alxmrs** [comment]
> Unfortunately, I couldn't locate the crs_wkt attribute in the metadata of any file.

Yes, that makes sense. Zarr does not yet have a convention to store this info quite yet. My recommendation to get this info is to download a shard of the raw data (e.g. `gs://gcp-public-data-arco-era5/raw/ERA5GRIB/HRES/Month/1979/197901_hres_cape.grb2`) and try to parse the CRS (and affine transform) via `gdalinfo`. 

https://gdal.org/programs/gdalinfo.html

For what it's worth, there is ambiguity in how we approach this issue. A good next step would be to describe a technical plan for how we could implement this feature (could be in this thread). 

I recommend checking out pyproj, too. https://pyproj4.github.io/pyproj/dev/index.html

This library may provide useful utilities that we can use out-of-the-box to define grid boundaries.
