### ISSUE TITLE
weather-mv ee has the potential to overwrite asset files in GCS bucket.

### ISSUE THREAD

**Issue by deepgabani8** [google/weather-tools#293]
When we provide --asset_location to `weather-mv ee` , it doesn't check if an asset is already present.
This wouldn't fail the pipeline or throw an error, but simply overwrite the asset in the bucket and provide the updated bucket path to the earth engine asset. (Since we are using COG-based ingestion, overwriting assets in the bucket affects the asset in the earth engine. Asset in the earth engine just points to the bucket for COG-based ingestion.)

Problematic Scenario:
When the asset is present in the bucket which is pointed by an earth engine `projects/my-project/assets/asset-1`. Now if the user wants to knowingly ingest the same image at `projects/my-project/assets/asset-2` in the earth engine. But the user accidentally provides the same GCS bucket location for the --asset_location argument. Then the earth engine's original asset's link to the bucket path would break because the pipeline would've overwritten the existing asset file in GCS bucket. This would possibly make the original asset-1 inaccessible from the earth engine.

Possible solutions:
- Do `ee.data.copyAsset` which would copy the same asset as the original and also skip processing.
- Add a command line argument for the user to specify force overwrite. Prevent by default.

**Comment by alxmrs** [comment]
I'm assuming that these solutions are mutually exclusive options (please correct me if I'm wrong). To follow the conventions of our tools so far, we should do the second one. To expand further: 
- Skip already-ingested assets.
- Document that we have a caching feature for ingesting (won't do duplicate ingests)
- Let users override this via a `-f,--force` flag. 


Thanks for identifying this problem and adding this writeup.
