### ISSUE TITLE
Fix Windows setup

### ISSUE THREAD

**Issue by CillianFn** [google/weather-tools#34]
**Issue:** 
When running the following setup command on Windows 10 (Python 3.8.5), 
`pip install -e ."[dev]"`

Getting the following error
`    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Cillian\Anaconda3\envs\py385\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'D:\\Projects\\weather-tools\\weather-tools\\setup.py'"'"'; __file__='"'"'D:\\Projects\\weather-tools\\weather-tools\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Cillian\AppData\Local\Temp\pip-pip-egg-info-ewy709ue'
         cwd: D:\Projects\weather-tools\weather-tools\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "D:\Projects\weather-tools\weather-tools\setup.py", line 66, in <module>
        long_description=open('README.md', 'r').read(),
      File "C:\Users\Cillian\Anaconda3\envs\py385\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 2775: character maps to <undefined>
    ----------------------------------------`

Explanation of issue: https://dev.to/methane/python-use-utf-8-mode-on-windows-212i

**Expected:**
Run command with no issue 

**Fix:** 
Update the following line https://github.com/google/weather-tools/blob/main/setup.py#L66 to include encoding
`long_description=open('README.md', 'r', encoding='utf-8').read(),`

@alxmrs I have a branch locally with this fix, happy to put up a PR but I seem to not have write permissions for this repo. Would appreciate getting those as I'd like to make more (interesting :wink: ) contributions in the future!

**Comment by alxmrs** [comment]
Hey @CillianFn! Thanks so much for raising attention to this – we're happy to have a windows developer to iron out issues on that platform. 

Glad to have your fix. Would you mind forking the repo? From there, you should be able to issue a PR.
