### ISSUE TITLE
`weather-dl`: Document the -n argument

### ISSUE THREAD

**Issue by alxmrs** [google/weather-tools#46]
In an oversight, a recent feature of `weather-dl` has not been documented. Let's make known to readers of the tool's README that the flag exists and describe what it does. Further, let's add a usage example.

**Comment by himanshu007-creator** [comment]
Hi, i would like to work on this issue. Please guide me further on what needs to be done

**Comment by alxmrs** [comment]
Sure thing. Please update the usage section of this doc: weather_dl/README.md

- install weather-dl and run --help on it
- copy the arg description of -n from there into the readme, following the existing format. 
- add a usage example in the example section below
