### ISSUE TITLE
Create example JSON config(s)

### ISSUE THREAD

**Issue by CillianFn** [google/weather-tools#47]
Similar to the `*.cfg` configuration file examples found in `/configs`, create example JSON config(s)

**Comment by pranay101** [comment]
Hi, I am new to open source and I would like to work on this issue. Please guide me further on what needs to be done.

**Comment by CillianFn** [comment]
Hey @pranay101 ! More information can be found about what configuration files are used for [here](https://github.com/google/weather-tools/blob/main/Configuration.md) 

As outlined, `Configuration files can be written in *.cfg or *.json`. However the examples in the [config](https://github.com/google/weather-tools/tree/main/configs) directory only contains examples of `*.cfg` files. 

It would be useful to have some `*.json` examples also. I suggest creating json versions of some of the cfg examples. These can then be tested locally to ensure the same behaviour is observed e.g. 

`weather-dl configs/era5_example_config_local_run.cfg --local-run
`
should work the same as, 
`weather-dl configs/era5_example_config_local_run.json--local-run
`

**Comment by alxmrs** [comment]
I like the idea of having JSON configs. It's worth noting that the JSON representation will not be as full featured as the ConfigParser. See: https://github.com/google/weather-tools/blob/main/weather_dl/download_pipeline/parsers.py#L72

I think we can still create JSON example configs; however, these will have to be more verbose for the time being.

**Comment by alxmrs** [comment]
xref: #48

**Comment by pranay101** [comment]
> Hey @pranay101 ! More information can be found about what configuration files are used for [here](https://github.com/google/weather-tools/blob/main/Configuration.md)
> 
> As outlined, `Configuration files can be written in *.cfg or *.json`. However the examples in the [config](https://github.com/google/weather-tools/tree/main/configs) directory only contains examples of `*.cfg` files.
> 
> It would be useful to have some `*.json` examples also. I suggest creating json versions of some of the cfg examples. These can then be tested locally to ensure the same behaviour is observed e.g.
> 
> `weather-dl configs/era5_example_config_local_run.cfg --local-run ` should work the same as, `weather-dl configs/era5_example_config_local_run.json--local-run `

how should I structure the project then?. creating separate folders for .CFG and .JSON inside config. or should I place json file along with the cfg files.

**Comment by alxmrs** [comment]
I'm a fan of flat file structures. So, json next to cfg sounds good to me.
