### ISSUE TITLE
Extend CI to test example configs are valid

### ISSUE THREAD

**Issue by alxmrs** [google/weather-tools#55]
Hey @CillianFn and @pranay101, this issue was inspired by #52 and #47. If either of you would like to pick this up, that would be a great help!

To summarize: we should start treating our configs like code and include them in our automated checks. For this issue to be fixed, we should add to our CI build to test that all the example configs parse correctly (check for correct syntax). For now, I think it's sufficient to run each config with the `-d, --dry-run` flag. Later, we can check that the semantics of the configs are correct.

**Comment by pranay101** [comment]
hey @alxmrs, it'll be great working on this issue. But this issue seems too technical to me right now can you please break it down a bit.

**Comment by alxmrs** [comment]
Given that #56 is merged, we can call this issue fixed.
