### ISSUE TITLE
`weather-dl`: Implement BigQuery manifest

### ISSUE THREAD

**Issue by alxmrs** [google/weather-tools#60]
Similar to #13, except the manifest should be a BigQuery table. This makes sense if users choose to use `weather-mv` and want their data queryable from one place.

**Comment by blackvvine** [comment]
Since we're taking the time to fix this, wouldn't Cloud Logging be a better substitute for BQ, GCS, and Firebase?

**Comment by alxmrs** [comment]
I'm less familiar with Cloud Logger. How would it help suit our needs here, which are primarily to have a central record of our download status?

**Comment by blackvvine** [comment]
[Cloud Logging](https://cloud.google.com/logging) is Stackdriver's new name, where Dataflow pipeline logs show up too. Since it's very unlikely that the users are interested in any complex analytics on the manifest logs, BQ is not a great option. Stackdriver is cheaper, easier to use, and the permissions are less complex to manage. 

I've created and tested a tiny Stackdriver manifest implementation [here](https://github.com/blackvvine/weather-tools/tree/stackdriver-manifest). The logs will show up in Cloud Console like this:

<img width="1241" alt="Screen Shot 2022-09-18 at 6 12 07 PM" src="https://user-images.githubusercontent.com/9886871/190930035-787c5b5a-b896-42f2-8c38-9e1b59d53c87.png">

**Comment by alxmrs** [comment]
What every the service / implementation, I ideally want to be able to answer the following questions quickly (say, with a local script or even a dashboard): 
- What data is currently in progress? What's queued for download? 
- What data have we already ingested? 
- Approximately, how long will it take to finish this job? 

Do you think that Cloud Logging would help us answer these questions? The `Manifest` is not really a logging system, but rather a database that we intend to query to answer these questions.

**Comment by alxmrs** [comment]
To put this feature in terms of a problem: Right now, our default implementation for the manifest is `Firestore`. We have a CLI script we include with `weather-dl` that checks what the current status is: 
https://github.com/google/weather-tools/blob/main/weather_dl/download-status

Unfortunately, due to our database choice and current number of records, this script is not performant + hits API limits right away. This inspiration for this issue was: 
- it would make much more sense if we used a traditional RDBMS instead of a key-value store
- we'd prefer to use BigQuery rather than other DB implementations to start, since our project is pretty wed to BQ.

**Comment by jayendra13** [comment]
How about using [custom metrics](https://cloud.google.com/monitoring/api/metrics_gcp), and having [monitoring dashboard](https://cloud.google.com/monitoring/dashboards) ?
This requires modification in the existing pipeline code, where it updates the our custom metrics, and dashboard will be able to show all things in the one place. 
This monitoring can be extended for alerting mechanism too.

**Comment by alxmrs** [comment]
I like the idea of using metrics to answer some of these questions. However, it looks like custom metrics [only last 30 days](https://cloud.google.com/dataflow/docs/guides/using-monitoring-intf), so they wouldn't solve the problem of having a record of what was downloaded.

**Comment by alxmrs** [comment]
Further, it looks like we could possibly run into [quota limits](https://cloud.google.com/monitoring/quotas) for storing values as metrics, whereas as traditional DB would allow us to have unlimited writes.

**Comment by mahrsee1997** [comment]
Closing this issue as it has been addressed by the changes made in PR #295 which has been merged.
