### ISSUE TITLE
Schedule open weather-tools developer meetings. 

### ISSUE THREAD

**Issue by alxmrs** [google/weather-tools#78]
To foment better community support of these tools, let's schedule a weekly 30 minute meeting for `weather-tools` developers. If you are interested in contributing to this codebase, please let us know what time(s) you are available to meet here: http://whenisgood.net/weather-tools-meeting

Once a date is found, we'll update the contributing docs with the time and steps to attend the weekly meetings.

**Comment by alxmrs** [comment]
CC: @CillianFn @saveriogzz @pranay101

**Comment by pranay101** [comment]
Hey @alxmrs did we finalise the date and time for a meet?

**Comment by alxmrs** [comment]
Thanks for following up. I'm going to announce the meetings soon – I'm waiting to hear back from a few more people.
